export const EVENTS = {
    SCORE_CHANGED: 'SCORE_CHANGED',
    UPDATE_BOARD: 'UPDATE_BOARD',
    NEXT_PIECE: 'NEXT_PIECE',
    HOLD_PIECE: 'HOLD_PIECE',
    STATE_CHANGED: 'STATE_CHANGED'
};

export const GAME_STATES = {
    TITLE: 'TITLE',
    PLAYING: 'PLAYING',
    PAUSED: 'PAUSED',
    GAME_OVER: 'GAME_OVER'
};